translate = {
    'weight'             : 'Váha',
    'price'              : 'Cena',
    'strength'           : 'Síla',
    'rampancy'           : 'Útočnost',
    'defence'            : 'Obrana',
    'weaponWeight'       : 'Váha zbraně',
    'handling'           : 'Držení',
    'length'             : 'Délka',
    'capacity'           : 'Kapacita',
    'copper'             : 'Měďáky',
    'silver'             : 'Stříbrnáky',
    'gold'               : 'Zlaťáky',
    'quality'            : 'Kvalita',
    'weightA'            : 'Váha A',
    'weightB'            : 'Váha B',
    'weightC'            : 'Váha C',
    'size'               : 'Velikost',
    'initiative'         : 'Iniciativa',
    'rangeLow'           : 'Dostřel krátký',
    'rangeMedium'        : 'Dostřel střední',
    'rangeHigh'          : 'Dostřel dlouhý',

    'class'              : 'Povolání',
    'mana_cost_initial'  : 'Mana pro vyčarování',
    'mana_cost_continual': 'Mana pro udržení',
    'range'              : 'Dosah',
    'scope'              : 'Rozsah',
    'cast_time'          : 'Doba vykouzlení',
    'duration'           : 'Trvání',
    'chance'             : 'Šance',
    'drd_race'           : 'Rasa',
    'drd_class'          : 'Povolání',
    'target'             : 'Cíl',
    'name'               : 'Jméno',
    'modifTarget'        : 'Cíl modifikátoru',
    'attrTarget'         : 'Cílový atribut',
    'valueType'          : 'Typ hodnoty',
    'value'              : 'Hodnota',
    'agility'            : 'Obratnost',
    'charisma'           : 'Charisma',
    'intelligence'       : 'Inteligence',
    'mobility'           : 'Pohyblivost',
    'toughness'          : 'Odelonost',
    'age'                : 'Věk',
    'height'             : 'Výška',
    'level'              : 'Levl',
    'xp'                 : 'Zkušenosti',
    'maxHealth'          : 'Maximální počet životů',
    'maxMana'            : 'Maximální množství many',
    'drdClass'           : 'Povolání',
    'drdRace'            : 'Rasa',
    'description'        : 'Popis',
    ''                   : '',
}
