translate = {
    'weight'                    : 'Weight',
    'price'                     : 'Price',
    'strength'                  : 'Strength',
    'rampancy'                  : 'Rampancy',
    'defence'                   : 'Defence',
    'weaponWeight'              : 'Weapon weight',
    'handling'                  : 'Handling',
    'length'                    : 'Length',
    'capacity'                  : 'Capacity',
    'copper'                    : 'Copper',
    'silver'                    : 'Silver',
    'gold'                      : 'Gold',
    'quality'                   : 'Quality',
    'weightA'                   : 'Weight A',
    'weightB'                   : 'Weight B',
    'weightC'                   : 'Weight C',
    'size'                      : 'Size',
    'initiative'                : 'Initiative',
    'rangeLow'                  : 'Range low',
    'rangeMedium'               : 'Range medium',
    'rangeHigh'                 : 'Range high',

    'class'                     : 'Class',
    'mana_cost_initial'         : 'Mana cost initial',
    'mana_cost_continual'       : 'Mana cost continual',
    'range'                     : 'Range',
    'scope'                     : 'Scope',
    'cast_time'                 : 'Cast time',
    'duration'                  : 'Duration',
    'chance'                    : 'Chance',
    'drd_race'                  : 'Race',
    'drd_class'                 : 'Class',
    'target'                    : 'Target',
    'name'                      : 'Name',
    'modifTarget'               : 'Modifier target',
    'attrTarget'                : 'Target attribute',
    'valueType'                 : 'Type of value',
    'value'                     : 'Value',
    'agility'                   : 'Agility',
    'charisma'                  : 'Charisma',
    'intelligence'              : 'Intelligence',
    'mobility'                  : 'Mobility',
    'toughness'                 : 'Toughness',
    'age'                       : 'Age',
    'height'                    : 'Height',
    'level'                     : 'Level',
    'xp'                        : 'Xp',
    'maxHealth'                 : 'Max health',
    'maxMana'                   : 'Max mana',
    'drdClass'                  : 'Class',
    'drdRace'                   : 'Race',
    'description'               : 'Description',
    'viability'                 : 'Viability',
    'offense'                   : 'Offense',
    'defense'                   : 'Defense',
    'endurance'                 : 'Endurance',
    'perseverance'              : 'Perseverance',
    'alignment'                 : 'Alignment',
    'experience'                : 'Experience',
    'hp'                        : 'Hp',
    'monsterRace'               : 'Race',

    'Spells'                    : 'Spells',
    'Abilities'                 : 'Abilities',
    'Effects'                   : 'Effects',
    'Modifiers'                 : 'Modifiers',
    'Characters'                : 'Characters',
    'Maps'                      : 'Maps',
    'Adventures'                : 'Adventures',
    'Locations'                 : 'Locations',
    'Party'                     : 'Party',
    'Ability_contexts'          : 'Ability contexts',
    'Items'                     : 'Items',
    'Monsters'                  : 'Monsters',


    'ALCHEMIST'                 : 'Alchemist',
    'MAGICIAN'                  : 'Magician',
    'RANGER'                    : 'Ranger',
    'THIEF'                     : 'Thief',
    'WARRIOR'                   : 'Warrior',

    # --------- Races -------------------------------------------------------
    'BARBARIAN'                 : 'Barbarian',
    'DWARF'                     : 'Dwarf',
    'ELF'                       : 'Elf',
    'HOBBIT'                    : 'Habbit',
    'HUMAN'                     : 'Human',
    'KROLL'                     : 'Kroll',
    'KUDUK'                     : 'Kuduk',

    # --------- Alignments -------------------------------------------------------
    'LAWFUL_GOOD'               : 'Lawful good',
    'CHAOTIC_GOOD'              : 'Chaotic good',
    'NEUTRAL'                   : 'Neutral',
    'CHAOTIC_EVIL'              : 'Chaotic evil',
    'LAWFUL_EVIL'               : 'Lawful evil',

    # --------- Handling -----------------------------------------------------
    'ONE_HANDED'                : 'One handed',
    'TWO_HANDED'                : 'Two handed',

    # --------- Weapon weight ------------------------------------------------
    'LIGHT'                     : 'Light',
    'MIDDLE'                    : 'Middle',
    'HEAVY'                     : 'Heavy',

    # --------- Modifier Target Types ------------------------------------------------
    'AFFECTS_ITEM'              : 'Item',
    'AFFECTS_CHARACTER'         : 'Character',
    'AFFECTS_MELEE_WEAPON'      : 'Melee weapon',
    'AFFECTS_RANGED_WEAPON'     : 'Ranged weapon',
    'AFFECTS_THROWABLE_WEAPON'  : 'Throwable weapon',
    'AFFECTS_ARMOR'             : 'Armor',
    'AFFECTS_CONTAINER'         : 'Container',
    'AFFECTS_MONEY'             : 'Money',
    'AFFECTS_ALL_ITEMS'         : 'All items',

    'CONTAINER_CAPACITY'        : 'Container capacity',
    'CONTAINER_WEIGHT'          : 'Container weight',
    'ARMOR_QUALITY'             : 'Armor quality',
    'ARMOR_SIZE'                : 'Armor size',
    'WEAPON_STRENGTH'           : 'Weapon strength',
    'WEAPON_RAMPANCY'           : 'Weapon rampancy',
    'WEAPON_DEFENCE'            : 'Weapon defence',
    'WEAPON_INITIATIVE'         : 'Weapon racial',
    'WEAPON_WEIGHT'             : 'Weapon weight',
    'WEAPON_MELEE_LENGTH'       : 'Weapon length',
    'WEAPON_MELEE_HANDLING'     : 'Weapon handling',
    'WEAPON_RANGED_RANGE_ALL'   : 'Ranged weapon strength (all)',
    'WEAPON_RANGED_RANGE_LOW'   : 'Ranged weapon strength (low)',
    'WEAPON_RANGED_RANGE_MEDIUM': 'Ranged weapon strength (medium)',
    'WEAPON_RANGED_RANGE_LONG'  : 'Ranged weapon strength (long)',

    'STRENGTH'                  : 'Strength',
    'AGILITY'                   : 'Agility',
    'TOUGHNESS'                 : 'Toughness',
    'INTELLIGENCE'              : 'Intelligence',
    'CHARISMA'                  : 'Charisma',
    'MOBILITY'                  : 'Mobility',
    'STRENGTH_BONUS'            : 'Strength bonus',
    'AGILITY_BONUS'             : 'Agility bonus',
    'TOUGHNESS_BONUS'           : 'Toughness bonus',
    'INTELLIGENCE_BONUS'        : 'Intelligence bonus',
    'CHARISMA_BONUS'            : 'Charisma bonus',
    'MOBILITY_BONUS'            : 'Mobility bonus',
    'HEALTH'                    : 'Health',
    'MANA'                      : 'Mana',
    'WEIGHT'                    : 'Weight',
    'HEIGHT'                    : 'Height',
    'OBSERVATION_RANDOM'        : 'Observation random',
    'OBSERVATION_SEARCHING'     : 'Observation searching',
    'OBSERVATION_MECHANISM'     : 'Observation mechanism',

    'TO_TOTAL'                  : '+ to total',
    'FROM_BASE'                 : '% from base',
    'FROM_TOTAL'                : '% from total',
    'None'                      : '---',
    ''                          : '',
    ''                          : '',
    ''                          : '',
}
