translate = {
    'weight'                    : 'Váha',
    'price'                     : 'Cena',
    'strength'                  : 'Síla',
    'rampancy'                  : 'Útočnost',
    'defence'                   : 'Obrana',
    'weaponWeight'              : 'Váha zbraně',
    'handling'                  : 'Držení',
    'length'                    : 'Délka',
    'capacity'                  : 'Kapacita',
    'copper'                    : 'Měďáky',
    'silver'                    : 'Stříbrnáky',
    'gold'                      : 'Zlaťáky',
    'quality'                   : 'Kvalita',
    'weightA'                   : 'Váha A',
    'weightB'                   : 'Váha B',
    'weightC'                   : 'Váha C',
    'size'                      : 'Velikost',
    'initiative'                : 'Iniciativa',
    'rangeLow'                  : 'Dostřel krátký',
    'rangeMedium'               : 'Dostřel střední',
    'rangeHigh'                 : 'Dostřel dlouhý',

    'class'                     : 'Povolání',
    'mana_cost_initial'         : 'Mana pro vyčarování',
    'mana_cost_continual'       : 'Mana pro udržení',
    'range'                     : 'Dosah',
    'scope'                     : 'Rozsah',
    'cast_time'                 : 'Doba vykouzlení',
    'duration'                  : 'Trvání',
    'chance'                    : 'Šance',
    'drd_race'                  : 'Rasa',
    'drd_class'                 : 'Povolání',
    'target'                    : 'Cíl',
    'name'                      : 'Jméno',
    'modifTarget'               : 'Cíl modifikátoru',
    'attrTarget'                : 'Cílový atribut',
    'valueType'                 : 'Typ hodnoty',
    'value'                     : 'Hodnota',
    'agility'                   : 'Obratnost',
    'charisma'                  : 'Charisma',
    'intelligence'              : 'Inteligence',
    'mobility'                  : 'Pohyblivost',
    'toughness'                 : 'Odolnost',
    'age'                       : 'Věk',
    'height'                    : 'Výška',
    'level'                     : 'Level',
    'xp'                        : 'Zkušenosti',
    'maxHealth'                 : 'Maximální počet životů',
    'maxMana'                   : 'Maximální množství many',
    'drdClass'                  : 'Povolání',
    'drdRace'                   : 'Rasa',
    'description'               : 'Popis',
    'viability'                 : 'Životaschopnost',
    'offense'                   : 'Útočné číslo',
    'defense'                   : 'Obranné číslo',
    'endurance'                 : 'Odolnost',
    'perseverance'              : 'Útočnost',
    'alignment'                 : 'Přesvědčení',
    'experience'                : 'Zkušenosti',
    'hp'                        : 'Životy',
    'monsterRace'               : 'Rasa',

    'Spells'                    : 'Kouzla',
    'Abilities'                 : 'Schopnosti',
    'Effects'                   : 'Efekty',
    'Modifiers'                 : 'Modifikátory',
    'Characters'                : 'Postavy',
    'Maps'                      : 'Mapy',
    'Adventures'                : 'Dobrodružství',
    'Locations'                 : 'Lokace',
    'Party'                     : 'Parta',
    'Ability_contexts'          : 'Contexty schopností',
    'Items'                     : 'Předměty',
    'Monsters'                  : 'Příšery',


    # ---------- Classes -----------------------------------------------------
    'ALCHEMIST'                 : 'Alchymista',
    'MAGICIAN'                  : 'Mág',
    'RANGER'                    : 'Hraničář',
    'THIEF'                     : 'Zloděj',
    'WARRIOR'                   : 'Válečník',

    # --------- Races -------------------------------------------------------
    'BARBARIAN'                 : 'Barbar',
    'DWARF'                     : 'Trpaslík',
    'ELF'                       : 'Elf',
    'HOBBIT'                    : 'Hobit',
    'HUMAN'                     : 'Člověk',
    'KROLL'                     : 'Krol',
    'KUDUK'                     : 'Kuduk',

    # --------- Alignments -------------------------------------------------------
    'LAWFUL_GOOD'               : 'Zákonné dobro',
    'CHAOTIC_GOOD'              : 'Zmatené dobro',
    'NEUTRAL'                   : 'Neutrální',
    'CHAOTIC_EVIL'              : 'Zmatené zlo',
    'LAWFUL_EVIL'               : 'Zákonné zlo',

    # --------- Handling -----------------------------------------------------
    'ONE_HANDED'                : 'Jednoruční',
    'TWO_HANDED'                : 'Obouruční',

    # --------- Weapon weight ------------------------------------------------
    'LIGHT'                     : 'Lehká',
    'MIDDLE'                    : 'Střední',
    'HEAVY'                     : 'Těžká',

    # --------- Modifier Target Types ------------------------------------------------
    'AFFECTS_ITEM'              : 'Předmět',
    'AFFECTS_CHARACTER'         : 'Postava',
    'AFFECTS_MELEE_WEAPON'      : 'Znraň na blízko',
    'AFFECTS_RANGED_WEAPON'     : 'Zbraň na dálku',
    'AFFECTS_THROWABLE_WEAPON'  : 'Vrhací zbraň',
    'AFFECTS_ARMOR'             : 'Brnění',
    'AFFECTS_CONTAINER'         : 'Kontejner',
    'AFFECTS_MONEY'             : 'Peníze',
    'AFFECTS_ALL_ITEMS'         : 'Všechny předměty',

    'WEIGHT'                    : 'Váha',
    'CONTAINER_CAPACITY'        : 'Kapacita kontejneru',
    'CONTAINER_WEIGHT'          : 'Váha kontejneru',
    'ARMOR_QUALITY'             : 'Kvalita brnění',
    'ARMOR_SIZE'                : 'Velikost brnění',
    'WEAPON_STRENGTH'           : 'Síla zbraně',
    'WEAPON_RAMPANCY'           : 'Útočnost zbraně',
    'WEAPON_DEFENCE'            : 'Obrana zbraně',
    'WEAPON_INITIATIVE'         : 'Iniciativa zbraně',
    'WEAPON_WEIGHT'             : 'Váha zbraně',
    'WEAPON_MELEE_LENGTH'       : 'Délka zbraně',
    'WEAPON_MELEE_HANDLING'     : 'Držení zbraně',
    'WEAPON_RANGED_RANGE_ALL'   : 'Síla zbraně na dálku (všechny)',
    'WEAPON_RANGED_RANGE_LOW'   : 'Síla zbraně na dálku (krátký)',
    'WEAPON_RANGED_RANGE_MEDIUM': 'Síla zbraně na dálku (střední)',
    'WEAPON_RANGED_RANGE_LONG'  : 'Síla zbraně na dálku (dlouhý)',

    'STRENGTH'                  : 'Síla',
    'AGILITY'                   : 'Obratnost',
    'TOUGHNESS'                 : 'Odolnost',
    'INTELLIGENCE'              : 'Inteligence',
    'CHARISMA'                  : 'Charisma',
    'MOBILITY'                  : 'Pohyblivost',
    'STRENGTH_BONUS'            : 'Bonus k síle',
    'AGILITY_BONUS'             : 'Bonus k obratnosti',
    'TOUGHNESS_BONUS'           : 'Bonus k odolnosti',
    'INTELLIGENCE_BONUS'        : 'Bonus k inteligenci',
    'CHARISMA_BONUS'            : 'Bonus k charisma',
    'MOBILITY_BONUS'            : 'Bonus k pohyblivosti',
    'HEALTH'                    : 'Životy',
    'MANA'                      : 'Mana',
    'WEIGHT'                    : 'Váha',
    'HEIGHT'                    : 'Výška',
    'OBSERVATION_RANDOM'        : 'Pozorování náhodné',
    'OBSERVATION_SEARCHING'     : 'Pozorování hledání',
    'OBSERVATION_MECHANISM'     : 'Pozorování mechanismy',

    'TO_TOTAL'                  : '+ k celku',
    'FROM_BASE'                 : '% ze základu',
    'FROM_TOTAL'                : '% z celku',
    'None'                      : '---',
    ''                          : '',
    ''                          : '',
    ''                          : '',
}
