translate = {
    'weight'             : 'Váha',
    'price'              : 'Cena',
    'strength'           : 'Síla',
    'rampancy'           : 'Útočnost',
    'defence'            : 'Obrana',
    'weaponWeight'       : 'Váha zbraně',
    'handling'           : 'Držení',
    'length'             : 'Délka',
    'capacity'           : 'Kapacita',
    'copper'             : 'Měďáky',
    'silver'             : 'Stříbrnáky',
    'gold'               : 'Zlaťáky',
    'quality'            : 'Kvalita',
    'weightA'            : 'Váha A',
    'weightB'            : 'Váha B',
    'weightC'            : 'Váha C',
    'size'               : 'Velikost',
    'initiative'         : 'Iniciativa',
    'rangeLow'           : 'Dostřel krátký',
    'rangeMedium'        : 'Dostřel střední',
    'rangeHigh'          : 'Dostřel dlouhý',

    'class'              : 'Povolání',
    'mana_cost_initial'  : 'Mana pro vyčarování',
    'mana_cost_continual': 'Mana pro udržení',
    'range'              : 'Dosah',
    'scope'              : 'Rozsah',
    'cast_time'          : 'Doba vykouzlení',
    'duration'           : 'Trvání',
    ''                   : '',
    ''                   : '',
    ''                   : '',
}
