# -*- coding: utf-8 -*-

translate = {
    'Menu_file'                 : '&Soubor',
    'Menu_exit'                 : '&Konec',
    'Menu_open'                 : '&Otevřít',
    'Menu_help'                 : '&Nápověda',
    'Menu_about'                : '&O aplikaci',
    'Menu_save'                 : 'Uložit',
    'Menu_settings'             : 'Nastavení',

    'Menu.spell'                : 'Šablony kouzel',
    'Menu.ability'              : 'Šablony schopností',
    'Menu.item'                 : 'Předměty',
    'Menu.templates'            : 'Šablony',
    'Menu.effect'               : 'Efekty',
    'Menu.modifier'             : 'Modifikátory',
    'Menu.character'            : 'Postavy',
    'Menu.monster'              : 'Příšery',
    'Menu.scenario'             : 'Dobrodružství',
    'Menu.location'             : 'Lokace',
    'Menu.abilityContext'       : 'Kontext pro schopnosti',


    'Name'                      : 'Jméno',
    'Description'               : 'Popis',
    'Mana_cost_initial'         : 'Počáteční cena',
    'Mana_cost_continual'       : 'Cena pro udržení',
    'Range'                     : 'Dosah',
    'Scope'                     : 'Rozsah',
    'Cast_time'                 : 'Doba vyčarování',
    'Duration'                  : 'Trvání',
    'Class'                     : 'Povolání',
    'Race'                      : 'Rasa',
    'Chance'                    : 'Šance',
    'Weight'                    : 'Váha',
    'Price'                     : 'Cena',
    'Copper'                    : 'Mědáky',
    'Silver'                    : 'Stříbrňáky',
    'Gold'                      : 'Zlaťáky',
    'Initiative'                : 'Iniciativa',
    'Strength'                  : 'Síla',
    'Rampancy'                  : 'Útočnost',
    'RangeLow'                  : 'Range low',
    'RangeMedium'               : 'Range medium',
    'RangeHigh'                 : 'Range high',
    'Defence'                   : 'Obrana',
    'WeaponWeight'              : 'Váha zbraně',
    'Handling'                  : 'Držení',
    'Length'                    : 'Délka',
    'Size'                      : 'Velikost',
    'Quality'                   : 'Kvalita',
    'Capacity'                  : 'Kapacita',
    'Amount'                    : 'Množství',


    'Folder'                    : 'Složka',
    'NodeObject'                : 'Objekt',
    'Type'                      : 'Typ',
    'Code'                      : 'Kód',
    'Select_lang'               : 'Vybrat jazyk',
    'Create_new_lang'           : 'Vytvořit nový',
    'Select_value'              : 'Vyberte možnost',


    'ObjectType.SPELL'          : 'Kouzla',
    'ObjectType.ABILITY'        : 'Schopnosti',
    'ObjectType.ITEM'           : 'Předměty',
    'ObjectType.MODIFIER'       : 'Modifikátory',
    'ObjectType.EFFECT'         : 'Efekty',
    'ObjectType.CHARACTER'      : 'Postavy',
    'ObjectType.MONSTER'        : 'Příšery',
    'ObjectType.SCENARIO'       : 'Dobrodružství',
    'ObjectType.LOCATION'       : 'Lokace',
    'ObjectType.ABILITY_CONTEXT': 'Kontext pro chopnosti',
    'ObjectType.MAP'            : 'Mapy',

    'Items.GENERIC'             : ' Předmět',
    'Items.CONTAINER'           : 'Kontejner',
    'Items.MELEE_WEAPON'        : 'Zbraň na blízko',
    'Items.RANGED_WEAPON'       : 'Zbraň na dálku',
    'Items.THROWABLE_WEAPON'    : 'Vrhací zbraň',
    'Items.ARMOR'               : 'Brnění',
    'Items.MONEY'               : 'Peníze',


    'NodeType.FOLDER'           : 'Složka',
    'NodeType.OBJECT'           : 'Objekt',

    # ---------- Classes -----------------------------------------------------
    'ALCHEMIST'                 : 'Alchymista',
    'MAGICIAN'                  : 'Mág',
    'RANGER'                    : 'Hraničář',
    'THIEF'                     : 'Zloděj',
    'WARRIOR'                   : 'Válečník',

    # --------- Races -------------------------------------------------------
    'BARBARIAN'                 : 'Barbar',
    'DWARF'                     : 'Trpaslík',
    'ELF'                       : 'Elf',
    'HOBBIT'                    : 'Hobit',
    'HUMAN'                     : 'Člověk',
    'KROLL'                     : 'Krol',
    'KUDUK'                     : 'Kuduk',

    # --------- Alignments -------------------------------------------------------
    'LAWFUL_GOOD'               : 'Zákonné dobro',
    'CHAOTIC_GOOD'              : 'Zmatené dobro',
    'NEUTRAL'                   : 'Neutrální',
    'CHAOTIC_EVIL'              : 'Zmatené zlo',
    'LAWFUL_EVIL'               : 'Zákonné zlo',

    # --------- Handling -----------------------------------------------------
    'ONE_HANDED'                : 'Jednoruční',
    'TWO_HANDED'                : 'Obouruční',

    # --------- Weapon weight ------------------------------------------------
    'LIGHT'                     : 'Lehká',
    'MIDDLE'                    : 'Střední',
    'HEAVY'                     : 'Těžká',

    # --------- Modifier Target Types ------------------------------------------------
    'AFFECTS_ITEM'              : 'Předmět',
    'AFFECTS_CHARACTER'         : 'Postava',
    'AFFECTS_MELEE_WEAPON'      : 'Znraň na blízko',
    'AFFECTS_RANGED_WEAPON'     : 'Zbraň na dálku',
    'AFFECTS_THROWABLE_WEAPON'  : 'Vrhací zbraň',
    'AFFECTS_ARMOR'             : 'Brnění',
    'AFFECTS_CONTAINER'         : 'Kontejner',
    'AFFECTS_MONEY'             : 'Peníze',

    'WEIGHT'                    : 'Váha',
    'CONTAINER_CAPACITY'        : 'Kapacita kontejneru',
    'CONTAINER_WEIGHT'          : 'Váha kontejneru',
    'ARMOR_QUALITY'             : 'Kvalita brnění',
    'ARMOR_SIZE'                : 'Velikost brnění',
    'WEAPON_STRENGTH'           : 'Síla zbraně',
    'WEAPON_RAMPANCY'           : 'Útočnost zbraně',
    'WEAPON_DEFENCE'            : 'Obrana zbraně',
    'WEAPON_INITIATIVE'         : 'Iniciativa zbraně',
    'WEAPON_WEIGHT'             : 'Váha zbraně',
    'WEAPON_MELEE_LENGTH'       : 'Délka zbraně',
    'WEAPON_MELEE_HANDLING'     : 'Držení zbraně',
    'WEAPON_RANGED_RANGE_ALL'   : 'Síla zbraně na dálku (všechny)',
    'WEAPON_RANGED_RANGE_LOW'   : 'Síla zbraně na dálku (krátký)',
    'WEAPON_RANGED_RANGE_MEDIUM': 'Síla zbraně na dálku (střední)',
    'WEAPON_RANGED_RANGE_LONG'  : 'Síla zbraně na dálku (dlouhý)',

    'STRENGTH'                  : 'Síla',
    'AGILITY'                   : 'Obratnost',
    'TOUGHNESS'                 : 'Odolnost',
    'INTELLIGENCE'              : 'Inteligence',
    'CHARISMA'                  : 'Charisma',
    'MOBILITY'                  : 'Pohyblivost',
    'STRENGTH_BONUS'            : 'Bonus k síle',
    'AGILITY_BONUS'             : 'Bonus k obratnosti',
    'TOUGHNESS_BONUS'           : 'Bonus k odolnosti',
    'INTELLIGENCE_BONUS'        : 'Bonus k inteligenci',
    'CHARISMA_BONUS'            : 'Bonus k charisma',
    'MOBILITY_BONUS'            : 'Bonus k pohyblivosti',
    'HEALTH'                    : 'Životy',
    'MANA'                      : 'Mana',
    'WEIGHT'                    : 'Váha',
    'HEIGHT'                    : 'Výška',
    'OBSERVATION_RANDOM'        : 'Pozorování náhodné',
    'OBSERVATION_SEARCHING'     : 'Pozorování hledání',
    'OBSERVATION_MECHANISM'     : 'Pozorování mechanismy',

    'TO_TOTAL'                  : '+ k celku',
    'FROM_BASE'                 : '% ze základu',
    'FROM_TOTAL'                : '% z celku',

    'Effect_target'             : 'Cíl efektu',

    'Delete'                    : 'Smazat',
    'New_item'                  : 'Přidat objekt',
    'Import'                    : 'Importovat',
    'Rename'                    : 'Přejmenovat',
    'Add_object'                : 'Přidat jiný objekt',

    'New_name'                  : 'Nový název',

    'tip.New_root_node'         : 'Přidat kořenový objekt',
    'tip.Import_templates'      : 'Importovat šabblony',
    'tip.Export_templates'      : 'Exportovat šabblony',

    'Target_type'               : 'Cíl modifikátoru',
    'Target_attribute_type'     : 'Cílový atribut',
    'Value_type'                : 'Typ hodnoty',
    'Value'                     : 'Hodnota',

    'File_select_target'        : 'Zvolte cílový soubor',
    'File_select_open'          : 'Vyberte cílový soubor',

    'Viability'                 : 'Životaschop',
    'Offense'                   : 'Útočné číslo',
    'Defense'                   : 'Obranné číslo',
    'Endurance'                 : 'Odolnost',
    'Mobility'                  : 'Pohyblivost',
    'Perseverance'              : 'Vytrvalost',
    'Intelligence'              : 'Inteligence',
    'Charisma'                  : 'Charisma',
    'Alignment'                 : 'Přesvědčení',
    'Experience'                : 'Zkušenosti',
    'Hp'                        : 'Životy',
    'Monster_race'              : 'Rasa',
    'Monster_size'              : 'Velikost',
    'Agility'                   : 'Pohyblivost',
    'Toughness'                 : 'Odolnost',
    'Age'                       : 'Věk',
    'Height'                    : 'Výška',
    'Level'                     : 'Levl',
    'Xp'                        : 'Zkušenosti',
    'MaxHealth'                 : 'Maximální počet životů',
    'MaxMana'                   : 'Maximální množství many',
    'CurrentHealth'             : 'Aktuální počet životů',
    'CurrentMana'               : 'Aktuální monžství many',
    'Date'                      : 'Datum',
    ''                          : '',

    'DRAGON'                    : 'Drak',
    'ANIMAL'                    : 'Zvíře',
    'INSECT'                    : 'Hmyz',
    'UNDEAD'                    : 'Nemrtvý',
    'HUMANOID'                  : 'Humanoidní',
    'MYTHIC'                    : 'Mýtický',
    'OTHERS'                    : 'Ostatní',

    'A0'                        : 'Velikost A0',
    'A'                         : 'Velikost A',
    'B'                         : 'Velikost B',
    'C'                         : 'Velikost C',
    'D'                         : 'Velikost D',
    'E'                         : 'Velikost E',

}
