# -*- coding: utf-8 -*-

translate = {
    'Menu_file'                                 : '&Soubor',
    'Menu_exit'                                 : '&Konec',
    'Menu_open'                                 : '&Otevřít',
    'Menu_help'                                 : '&Nápověda',
    'Menu_about'                                : '&O aplikaci',

    'Menu.spell'                                : 'Šablony kouzel',
    'Menu.ability'                              : 'Šablony schopností',
    'Menu.item'                                 : 'Předměty',
    'Menu.templates'                            : 'Šablony',
    'Menu.effect'                               : 'Efekty',
    'Menu.modifier'                             : 'Modifikátory',

    'Name'                                      : 'Jméno',
    'Description'                               : 'Popis',
    'Mana_cost_initial'                         : 'Počáteční cena',
    'Mana_cost_continual'                       : 'Cena pro udržení',
    'Range'                                     : 'Dosah',
    'Scope'                                     : 'Rozsah',
    'Cast_time'                                 : 'Doba vyčarování',
    'Duration'                                  : 'Trvání',
    'Class'                                     : 'Povolání',
    'Race'                                      : 'Rasa',
    'Chance'                                    : 'Šance',
    'Weight'                                    : 'Váha',
    'Price'                                     : 'Cena',
    'Copper'                                    : 'Mědáky',
    'Silver'                                    : 'Stříbrňáky',
    'Gold'                                      : 'Zlaťáky',
    'Initiative'                                : 'Iniciativa',
    'Strength'                                  : 'Síla',
    'Rampancy'                                  : 'Útočnost',
    'RangeLow'                                  : 'Range low',
    'RangeMedium'                               : 'Range medium',
    'RangeHigh'                                 : 'Range high',
    'Defence'                                   : 'Obrana',
    'WeaponWeight'                              : 'Váha zbraně',
    'Handling'                                  : 'Držení',
    'Length'                                    : 'Délka',
    'Size'                                      : 'Velikost',
    'Quality'                                   : 'Kvalita',
    'Capacity'                                  : 'Kapacita',


    'Folder'                                    : 'Složka',
    'Object'                                    : 'Objekt',
    'Type'                                      : 'Typ',
    'Code'                                      : 'Kód',
    'Select_lang'                               : 'Vybrat jazyk',
    'Create_new_lang'                           : 'Vytvořit nový',
    'Select_value'                              : 'Vyberte možnost',


    'ObjectType.SPELL'                          : 'Kouzla',
    'ObjectType.ABILITY'                        : 'Schopnosti',
    'ObjectType.ITEM'                           : 'Předměty',
    'ObjectType.MODIFIER'                       : 'Modifikátory',
    'ObjectType.EFFECT'                         : 'Efekty',

    'NodeType.FOLDER'                           : 'Složka',
    'NodeType.OBJECT'                           : 'Objekt',

    'Classes.ALCHEMIST'                         : 'Alchymista',
    'Classes.MAGICIAN'                          : 'Mág',
    'Classes.RANGER'                            : 'Hraničář',
    'Classes.THIEF'                             : 'Zloděj',
    'Classes.WARRIOR'                           : 'Válečník',

    'Races.BARBARIAN'                           : 'Barbar',
    'Races.DWARF'                               : 'Trpaslík',
    'Races.ELF'                                 : 'Elf',
    'Races.HOBBIT'                              : 'Hobit',
    'Races.HUMAN'                               : 'Člověk',
    'Races.KROLL'                               : 'Krol',
    'Races.KUDUK'                               : 'Kuduk',

    'Handling.ONE_HANDED'                       : 'Jednoruční',
    'Handling.TWO_HANDED'                       : 'Obouruční',

    'WeaponWeight.LIGHT'                        : 'Lehká',
    'WeaponWeight.MIDDLE'                       : 'Střední',
    'WeaponWeight.HEAVY'                        : 'Těžká',

    'ModifierTargetTypes.ITEM'                  : 'Předmět',
    'ModifierTargetTypes.CHARACTER'             : 'Postava',

    'ItemsAttributes.WEIGHT'                    : 'Váha',
    'ItemsAttributes.CONTAINER_CAPACITY'        : 'Kapacita kontejneru',
    'ItemsAttributes.CONTAINER_WEIGHT'          : 'Váha kontejneru',
    'ItemsAttributes.ARMOR_QUALITY'             : 'Kvalita brnění',
    'ItemsAttributes.ARMOR_SIZE'                : 'Velikost brnění',
    'ItemsAttributes.WEAPON_STRENGTH'           : 'Síla zbraně',
    'ItemsAttributes.WEAPON_RAMPANCY'           : 'Útočnost zbraně',
    'ItemsAttributes.WEAPON_DEFENCE'            : 'Obrana zbraně',
    'ItemsAttributes.WEAPON_INITIATIVE'         : 'Iniciativa zbraně',
    'ItemsAttributes.WEAPON_WEIGHT'             : 'Váha zbraně',
    'ItemsAttributes.WEAPON_MELEE_LENGTH'       : 'Délka zbraně',
    'ItemsAttributes.WEAPON_MELEE_HANDLING'     : 'Držení zbraně',
    'ItemsAttributes.WEAPON_RANGED_RANGE_ALL'   : 'Síla zbraně na dálku (všechny)',
    'ItemsAttributes.WEAPON_RANGED_RANGE_LOW'   : 'Síla zbraně na dálku (krátký)',
    'ItemsAttributes.WEAPON_RANGED_RANGE_MEDIUM': 'Síla zbraně na dálku (střední)',
    'ItemsAttributes.WEAPON_RANGED_RANGE_LONG'  : 'Síla zbraně na dálku (dlouhý)',

    'CharacterAttributes.STRENGTH'              : 'Síla',
    'CharacterAttributes.AGILITY'               : 'Obratnost',
    'CharacterAttributes.TOUGHNESS'             : 'Odolnost',
    'CharacterAttributes.INTELLIGENCE'          : 'Inteligence',
    'CharacterAttributes.CHARISMA'              : 'Charisma',
    'CharacterAttributes.MOBILITY'              : 'Pohyblivost',
    'CharacterAttributes.STRENGTH_BONUS'        : 'Bonus k síle',
    'CharacterAttributes.AGILITY_BONUS'         : 'Bonus k obratnosti',
    'CharacterAttributes.TOUGHNESS_BONUS'       : 'Bonus k odolnosti',
    'CharacterAttributes.INTELLIGENCE_BONUS'    : 'Bonus k inteligenci',
    'CharacterAttributes.CHARISMA_BONUS'        : 'Bonus k charisma',
    'CharacterAttributes.MOBILITY_BONUS'        : 'Bonus k pohyblivosti',
    'CharacterAttributes.HEALTH'                : 'Životy',
    'CharacterAttributes.MANA'                  : 'Mana',
    'CharacterAttributes.WEIGHT'                : 'Váha',
    'CharacterAttributes.HEIGHT'                : 'Výška',
    'CharacterAttributes.OBSERVATION_RANDOM'    : 'Pozorování náhodné',
    'CharacterAttributes.OBSERVATION_SEARCHING' : 'Pozorování hledání',
    'CharacterAttributes.OBSERVATION_MECHANISM' : 'Pozorování mechanismy',

    'ModifierValueTypes.TO_TOTAL'               : '+ k celku',
    'ModifierValueTypes.FROM_BASE'              : '% ze základu',
    'ModifierValueTypes.FROM_TOTAL'             : '% z celku',


    'Delete'                                    : 'Smazat',
    'New_item'                                  : 'Přidat objekt',
    'Import'                                    : 'Importovat',
    'Rename'                                    : 'Přejmenovat',

    'New_name'                                  : 'Nový název',

    'tip.New_root_node'                         : 'Přidat kořenový objekt',
    'tip.Import_templates'                      : 'Importovat šabblony',
    'tip.Export_templates'                      : 'Exportovat šabblony',

    'Target_type'                               : 'Cíl modifikátoru',
    'Target_attribute_type'                     : 'Cílový atribut',
    'Value_type'                                : 'Typ hodnoty',
    'Value'                                     : 'Hodnota'


}
