# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created: Sat Feb  4 17:37:21 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 231, 501))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 510, 1021, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(230, 0, 771, 521))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(480, 90, 200, 194))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bezzubka.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 90, 351, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.velikostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.velikostLabel.setObjectName("velikostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.velikostLabel)
        self.velikostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.velikostLineEdit.setObjectName("velikostLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.velikostLineEdit)
        self.rychlostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.rychlostLabel.setObjectName("rychlostLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rychlostLabel)
        self.rychlostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rychlostLineEdit.setObjectName("rychlostLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rychlostLineEdit)
        self.vHaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.vHaLabel.setObjectName("vHaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vHaLabel)
        self.vHaLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.vHaLineEdit.setObjectName("vHaLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vHaLineEdit)
        self.ikovnostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.ikovnostLabel.setObjectName("ikovnostLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ikovnostLabel)
        self.ikovnostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ikovnostLineEdit.setObjectName("ikovnostLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ikovnostLineEdit)
        self.vKLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.vKLabel.setObjectName("vKLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.vKLabel)
        self.vKLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.vKLineEdit.setObjectName("vKLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.vKLineEdit)
        self.obratnostLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.obratnostLabel.setObjectName("obratnostLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.obratnostLabel)
        self.obratnostLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.obratnostLineEdit.setObjectName("obratnostLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.obratnostLineEdit)
        self.sLaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sLaLabel.setObjectName("sLaLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sLaLabel)
        self.sLaLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sLaLineEdit.setObjectName("sLaLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sLaLineEdit)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(30, 340, 711, 151))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(30, 320, 57, 15))
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(750, 9, 20, 501))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 500, 31, 21))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Plus Math-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 500, 31, 21))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Minus Math -48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 500, 31, 21))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.Czech, QtCore.QLocale.CzechRepublic))
        self.menuFile.setObjectName("menuFile")
        self.menuRozlo_en = QtWidgets.QMenu(self.menubar)
        self.menuRozlo_en.setObjectName("menuRozlo_en")
        self.menuO_aplikaci = QtWidgets.QMenu(self.menubar)
        self.menuO_aplikaci.setObjectName("menuO_aplikaci")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRozlo_en.menuAction())
        self.menubar.addAction(self.menuO_aplikaci.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dračí doupě"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Postavy"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Bytosti"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Hodné"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Elfové"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "Maiev"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("MainWindow", "Wisperwind"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).setText(0, _translate("MainWindow", "Windrunner"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Lidé"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "Uther"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).setText(0, _translate("MainWindow", "Arthas"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "Příšerky"))
        self.treeWidget.topLevelItem(0).child(0).child(2).child(0).setText(0, _translate("MainWindow", "Nejpříšernější"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Zlé"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Orkové"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(0).setText(0, _translate("MainWindow", "Thrall"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(1).setText(0, _translate("MainWindow", "Doomhammer"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Zlobři"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Bezzubka"))
        self.velikostLabel.setText(_translate("MainWindow", "Velikost:"))
        self.rychlostLabel.setText(_translate("MainWindow", "Rychlost:"))
        self.vHaLabel.setText(_translate("MainWindow", "Váha:"))
        self.ikovnostLabel.setText(_translate("MainWindow", "Šikovnost:"))
        self.vKLabel.setText(_translate("MainWindow", "Věk:"))
        self.obratnostLabel.setText(_translate("MainWindow", "Obratnost:"))
        self.sLaLabel.setText(_translate("MainWindow", "Síla:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Popis:</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "Soubor"))
        self.menuRozlo_en.setTitle(_translate("MainWindow", "Rozložení"))
        self.menuO_aplikaci.setTitle(_translate("MainWindow", "O aplikaci"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionNew.setText(_translate("MainWindow", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

